name: Release a CV

on:
  push:
    tags:
      - "*" # Any tag pushed to the repository
      
permissions:
  contents: write
  
jobs:
  call_rendercv_workflow:
    name: RenderCV
    uses: ./.github/workflows/rendercv.yaml

  build:
    needs: call_rendercv_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download RenderCV Output
        uses: actions/download-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rendercv_output/*_CV.pdf
            rendercv_output/*_CV.typ
            rendercv_output/*_CV.md
            rendercv_output/*_CV.png
          generate_release_notes: true
          make_latest: true

  deploy_pages:
    needs: call_rendercv_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download RenderCV Output
        uses: actions/download-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Remove non-html files before deploy
        run: |
          find rendercv_output ! -name '*.html' -type f -delete
      - name: Generate index.html for all HTML files
        run: |
          cat > rendercv_output/index.html <<'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Available CV HTML Files</title>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown-light.min.css" crossorigin="anonymous" />
            <style>
              body { background: #f6f8fa; }
              .markdown-body { max-width: 700px; margin: 40px auto; padding: 32px; background: #fff; border-radius: 8px; box-shadow: 0 2px 8px #0001; }
              ul { font-size: 1.2em; }
            </style>
          </head>
          <body>
            <article class="markdown-body">
              <h1>Available CV HTML Files</h1>
              <ul id="file-list"></ul>
            </article>
            <script>
              fetch('.')
                .then(response => response.text())
                .then(html => {
                  const parser = new DOMParser();
                  const doc = parser.parseFromString(html, 'text/html');
                  const links = Array.from(doc.querySelectorAll('a'))
                    .map(a => a.getAttribute('href'))
                    .filter(href => href && href.endsWith('.html') && href !== 'index.html');
                  const ul = document.getElementById('file-list');
                  if (links.length === 0) {
                    ul.innerHTML = '<li>No HTML files found.</li>';
                  } else {
                    links.forEach(href => {
                      const li = document.createElement('li');
                      li.innerHTML = `<a href="${href}">${href}</a>`;
                      ul.appendChild(li);
                    });
                  }
                });
            </script>
          </body>
          </html>
          EOF
      - name: Deploy HTML to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: rendercv_output
          publish_branch: gh-pages
          keep_files: false
          cname: ''
          force_orphan: true
          enable_jekyll: false