name: Release a CV

on:
  push:
    tags:
      - "*" # Any tag pushed to the repository
      
permissions:
  contents: write
  
jobs:
  call_rendercv_workflow:
    name: RenderCV
    uses: ./.github/workflows/rendercv.yaml

  build:
    needs: call_rendercv_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download RenderCV Output
        uses: actions/download-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rendercv_output/*_CV.pdf
            rendercv_output/*_CV.typ
            rendercv_output/*_CV.md
            rendercv_output/*_CV.png
          generate_release_notes: true
          make_latest: true

  deploy_pages:
    needs: call_rendercv_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download RenderCV Output
        uses: actions/download-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Remove non-html files before deploy
        run: |
          find rendercv_output ! -name '*.html' -type f -delete
      - name: Deploy HTML to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: rendercv_output
          publish_branch: gh-pages
          keep_files: false
          cname: ''
          force_orphan: true
          enable_jekyll: false